language: rust
rust: 1.36.0
dist: xenial
sudo: true
cache:
  directories:
    - $HOME/.cargo
  timeout: 1024

before_cache:
  - rm -rf $HOME/.cargo/registry

matrix:
  include:
    - name: Linter on macOS
      os: osx
      env: CACHE_NAME=linters
      install:
        - cargo fmt --version || travis_retry rustup component add rustfmt
        - cargo clippy --version || travis_retry rustup component add clippy
      script:
        - git diff-index --check --cached $$(git rev-parse --verify master 2>/dev/null || echo "1e9e43b42759e784e18c61fabaae6f9ab2dc20b7") --
        - cargo fmt --all -- --check
        - cargo clippy --all --all-targets --all-features
    - name: Test on macOS
      os: osx
      env: CACHE_NAME=Test
      script:
        - cargo test --all --all-targets --all-features
    - name: Test on macOS
      os: osx
      env: CACHE_NAME=Test
      script:
        - cargo test --all --all-targets --all-features
